[tools]
rust = "latest"
opentofu = "1.10"

[vars]
VAR_FILE = 'environments/{{get_env(name="ENV", default="dev")}}.tfvars'
BACKEND_FILE = 'backends/{{get_env(name="ENV", default="dev")}}.s3.tfbackend'
PLAN_FILE = 'tf.plan'


[tasks.openlinter]
run = "cargo run --"
